#! /bin/bash
#$ -clear
#$ -q 32c.q
#$ -cwd
#$ -V
#$ -S /bin/bash
#$ -o /scratch/gi/coop/perner/metameta/cluster_stdout
#$ -j y
#$ -t 21-23

# /work/gi/software/diamond-0.7.9/bin/./diamond makedb --in /scratch/gi/coop/perner/metameta/Pfam-A27.fasta.gz -d /scratch/gi/coop/perner/metameta/pfam27
# /work/gi/software/diamond-0.7.9/bin/./diamond blastx -d /scratch/gi/coop/perner/metameta/pfamA -q /scratch/gi/coop/perner/metameta/vents/xie_4143-1_33/preprocessed_reads/xie.fasta -a /scratch/gi/coop/perner/metameta/matches_xie -t /scratch/gi/coop/perner/metameta/temp
ruby /work/gi/coop/perner/metameta/meta_pipeline/diamond.rb /scratch/gi/coop/perner/metameta/vents/*_$SGE_TASK_ID
# ruby /work/gi/coop/perner/metameta/scripts/diamond_profile.rb /scratch/gi/coop/perner/metameta/vents/*_$SGE_TASK_ID
